# Generated by Django 5.0.3 on 2024-08-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_kesconuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesconuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
