# Generated by Django 5.0.3 on 2024-08-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_kesconuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kesconuser',
            managers=[
            ],
        ),
    ]
